import org.example.models.Order;

dialect  "java"

rule "$50 discount for order over $1000"
    no-loop
    when
          $order : Order(
           $order.getAmount() >= 1000 &&
           $order.getAmount() < 2000
          )
    then
        $order.setDiscount(50.0);
        $order.setAmountPayable($order.getAmount() - $order.getDiscount());
        update($order)
    end

rule "200 discount for order over $2000"
    no-loop
    when
          $order : Order(
               $order.getAmount() >= 2000
          )
    then
        $order.setDiscount(200.0);
        $order.setAmountPayable($order.getAmount() - $order.getDiscount());
        update($order)
    end