import org.example.models.Applicant;
import org.example.models.SuggestedRole;

dialect  "java"

rule "Suggest Manager Role"
    when
        $applicant : Applicant(
            $applicant.experienceInYears > 10 &&
            $applicant.currentSalary > 1000000 &&
            $applicant.currentSalary <= 2500000
        )
        $suggestedRole : SuggestedRole()
    then
        modify ( $suggestedRole ) {
            role = "Manager";
        }
    end